//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Life_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonRest
    {
        public int PersonID { get; set; }
        public int RestID { get; set; }
        public string Place { get; set; }
        public System.DateTime RestStart { get; set; }
        public System.DateTime RestEnd { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Rest Rest { get; set; }
    }
}
