//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Life_Tracker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int PersonID { get; set; }
        public string Day_Date { get; set; }
        public System.TimeSpan Start_Time { get; set; }
        public Nullable<System.TimeSpan> End_Time { get; set; }
        public string To_Do { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
